# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-14 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swim24app', '0002_tbls24counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbls24results',
            name='res_LastLapTime',
            field=models.DateTimeField(null=True),
        ),
    ]
