# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tritrainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distance',
            new_name='tblDistance',
        ),
        migrations.RenameModel(
            old_name='Results',
            new_name='tblResults',
        ),
        migrations.RenameModel(
            old_name='Sportsman',
            new_name='tblSportsman',
        ),
    ]
