# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tritrainapp', '0002_auto_20170620_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblresults',
            name='res_EndCicleTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tblresults',
            name='res_EndRunTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tblresults',
            name='res_EndSwimTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tblresults',
            name='res_StartCicleTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tblresults',
            name='res_StartRunTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tblresults',
            name='res_StartSwimTime',
            field=models.DateTimeField(null=True),
        ),
    ]
