# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tritrainapp', '0003_auto_20170623_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('al_user', models.CharField(max_length=64)),
                ('al_Timestamp', models.DateTimeField()),
                ('al_Action', models.IntegerField(default=0)),
                ('al_Comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tblresults',
            options={'ordering': ['res_EndRunTime', 'res_StartRunTime', 'res_EndCicleTime', 'res_StartCicleTime', 'res_EndSwimTime', 'res_StartSwimTime', 'res_Sportsman']},
        ),
    ]
