# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-07 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tritrainapp', '0004_auto_20170706_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblresults',
            options={},
        ),
        migrations.AlterField(
            model_name='tblresults',
            name='res_EndCicleTime',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='tblresults',
            name='res_EndRunTime',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='tblresults',
            name='res_EndSwimTime',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='tblresults',
            name='res_StartCicleTime',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='tblresults',
            name='res_StartRunTime',
            field=models.DurationField(null=True),
        ),
    ]
