# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dst_Name', models.CharField(max_length=200)),
                ('dst_SplitsNumber', models.IntegerField(default=0)),
                ('dst_Splits', models.IntegerField(default=0)),
                ('dst_Run', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tblDistanceSplits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_Distance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimrunapp.tblDistance')),
            ],
        ),
        migrations.CreateModel(
            name='tblDistanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dstTypeName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tblResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_SplitID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swimrunapp.tblDistanceSplits')),
            ],
        ),
        migrations.CreateModel(
            name='tblSplitsResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_SplitTime', models.DateTimeField(null=True)),
                ('sr_Split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimrunapp.tblDistanceSplits')),
                ('sr_SportsmanResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimrunapp.tblResult')),
            ],
        ),
        migrations.CreateModel(
            name='tblSportsman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_Name', models.CharField(max_length=200)),
                ('sm_Distance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimrunapp.tblDistance')),
            ],
        ),
        migrations.AddField(
            model_name='tblresult',
            name='res_Sportsman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimrunapp.tblSportsman'),
        ),
        migrations.AddField(
            model_name='tbldistancesplits',
            name='ds_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimrunapp.tblDistanceType'),
        ),
    ]
