# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swimrunapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbldistance',
            name='dst_Run',
        ),
        migrations.RemoveField(
            model_name='tbldistance',
            name='dst_Splits',
        ),
    ]
