# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimrunapp', '0002_auto_20170627_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbldistancetype',
            old_name='dstTypeName',
            new_name='dt_Name',
        ),
        migrations.AddField(
            model_name='tbldistancesplits',
            name='ds_Length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbldistancesplits',
            name='ds_SplitID',
            field=models.IntegerField(default=0),
        ),
    ]
